pages/dev/dev-env.mdx
Trying out the tabs feature of nextra [0], to organize the per-platform install docs.
[0] https://nextra.site/docs/guide/built-ins/tabs
=> feat: use tabs in dev env docs

pages/dev/dev-env.mdx, pages/dev/docs.md
Now that we've broken out the guide into its own repo, we need to be clearer about where the various docs static sites should be edited. Refs corresponding changes in https://github.com/penumbra-zone/penumbra/pull/4751
=> fix: update docs build in dev guide

pages/gov.mdx, pages/web/vote.mdx
This adds general documentation for governance, and a brief blurb about using void.vote.
The void.vote website is relatively self explanatory, but we could add some screenshots as well, in a subsequent pr.
PCLI was already well documented.
=> Add governance docs

pages/node/pd/chain-upgrade.mdx, pages/node/pd/install.mdx, penumbra_versions.js
Back when the guide was managed in the Penumbra protocol repo [0], the version strings in the docs were automatically bumped in line with the source code changes. Since breaking the guide out into a separate repo, we no longer have the convenience of those automatic updates, so the guide versions will necessarily lag behind. Let's remove the hardcoded version strings from crucial reference pages like the chain-upgrade docs, leaning on node operators to choose the correct version for a given upgrade.
[0] https://github.com/penumbra-zone/penumbra
=> feat: remove hardcoded versions in chain-upgrade docs

pages/node/pd/indexing-events.md, pages/relayers.md
First pass at making sure the necessary steps for updating relayers across upgrade boundaries are well documented.
=> docs: ibc relaying and chain upgrades

pages/pcli/_meta.json, pages/pcli/migrating.md
Adds a short explainer for how the `pcli migrate balance` functionality works. Refs:
* https://github.com/penumbra-zone/penumbra/issues/4831
* https://github.com/penumbra-zone/penumbra/issues/4849
=> docs: add 'pcli migrate balance' explainer

pages/node/pd/indexing-events.md
=> Describe using pindexer

pages/dev/parameter_setup.md
these were a bit out of date, this is from re-running benchmarks today on mainnet circuits
=> update zk benchmarks with mainnet circuit constraint count

pages/dev/_meta.json, pages/dev/testnet.md
Adds a new dev docs page that provides details on accessing the currently running testnet. We don't yet have a solution for a faucet, so the docs will need to be updated to be useful to external developers, but I'm submitting this PR anyway because this information is necessary, but not sufficient.
Refs https://github.com/penumbra-zone/guide/issues/35
=> docs: add testnet service endpoints

pages/node/pd/running-node.mdx
I was reading the [full node tutorial](https://guide.penumbra.zone/node/pd/running-node) and found a couple 404 links.
=> Corrected broken links in running-node.mdx

pages/dev/testnet.md
Now that the `penumbra-testnet-phobos-2` chain has been upgraded to `v0.81.0`, newly joining nodes will need to use a snapshot.
=> feat: add snapshot reference for testnet

flake.nix
This was always required, but was omitted in the flake env, causing `node` from system PATH to be used. It's more explicit to track a compatible version, so that `just dev` works out of the box for nix users.
=> build: add nodejs dep to flake env

pages/node/pd/join-network.md
Now that the `penumbra-1` chain has been upgraded to `v0.81.0`, newly joining nodes will need to use a snapshot. This was actually true as soon as that chain started running `v0.80.x`, but we weren't previously pointing to snapshots in the docs.
=> feat: add snapshot reference for mainnet

pages/resources.md
These URLs were shared by Ember of Radiant Commons as recent talks worth publishing links to.
=> docs: add recent talks to resources page

pages/node/pd/install.mdx, penumbra_versions.js
The cometbft version bump is updated to include 0.37.15, to include patches to security issues. See details in [0].
[0] https://github.com/cometbft/cometbft/blob/v0.37.15/CHANGELOG.md#v03715
=> chore: update pd & cometbft versions

.github/workflows/firebase-hosting-merge.yml, .github/workflows/firebase-hosting-pull-request.yml
PR #68 was showing deprecation notices on the DS helpers. Switching to what we use elsewhere.
=> ci: switch to maintained nix action helpers

pages/dev/testnet.mdx
Added mention of the chain recreation, for `penumbra-testnet-phobos-3`, with an explicit reference to the feature branch required for compatibility.
=> update testnet docs for phobos-3

pages/dev/_meta.json, pages/dev/build.mdx, pages/dev/dev-env.mdx
The first impression in the developer docs is now an explanation of building the repo from source, after manually installing dependencies. There's still a link-out to the escape hatch of using nix, for those who want the automated setup.
Closes #46.
=> refactor: de-prioritize nix docs for dev env

pages/dev/testnet.mdx
Once upon a time, we used galileo [0] as testnet faucet. More recently, since we have working IBC channels on the testnet, we can lean on faucets for counterparty chains, emphasizing that no native testnet tokens are required to get started.
[0] https://github.com/penumbra-zone/galileo/
=> describe testnet ibc channels in lieu of faucet

pages/dev/metrics.md
We've had the `measure` tool for ages, but it wasn't explicitly documented anywhere. Adding a primer on it, to aid operators in setting up RPCs for the first time.
=> document "measure" tool for generating traffic

.gitignore, flake.nix, justfile, next.config.mjs, package.json, pages/event-indexing/_meta.json, pages/event-indexing/architecture.mdx, pages/event-indexing/penumbra-events-pipeline.mermaid, pnpm-lock.yaml
Let's add an overview of how events pipelines are structured in Penumbra. We want the overall layout to be comprehensible by a node operator, so they can plan how best to host the infrastructure for their teams.
Here's an exported PNG of the architecture diagram, for easy reference:
Follow-up to #73.
=> add architecture diagram for events pipeline

pages/dev/build.mdx
Running Ubuntu 25.04, successful compile needed:
`sudo apt make libdbus-1-dev libusb-1.0-0-dev`
=> Update build.mdx instructions, Ubuntu 25.04

pages/dev/abci-events.md
Adds a few illustrative queries, to encourage a developer in exploring the db for the first time.
Follow-up to #73 & #74.
=> docs: sql abci event examples

pages/dev/ibc.md, pages/relayers.md
Removes mention of the PL-maintained Hermes fork, because upstream Hermes has all the requisite functionality for Penumbra.
=> docs: hermes upstream is penumbra-compatible
